# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt  # type d'encodage pour le mot de passe

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username # indique à SF où aller chercher la liste des utilisateurs

    firewalls:
        dev: # firewall pour la barre de développement
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false
        main: # firewall principal
            pattern: ^/ # actif sur l'ensemble du site
            form_login:
                provider: fos_userbundle 
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control: # définit les règles d'accès aux différentes parties du site
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } # autorisé pour les utilisateurs non authentifiés
        - { path: ^/admin, role: ROLE_ADMIN } # autorisé uniquement pour les utilisateur authentifiés dont le role est ROLE_ADMIN